"""Persistence backend smoke matrix.

Verifies the actual semantics of each backend exposed by the example
dispatcher's ``--backend`` flag:

- ``none``     → stateless: no data loaded from disk, no scenario persistence.
- ``json``     → DATA persists (StatefulDataManager loads serialised data
                 from the data folder); scenario *registry* is in-memory only.
                 Auto-created scenarios reappear on restart because they're
                 regenerated by ``autocreate=True``, not deserialised.
- ``database`` → DATA + SCENARIOS both persist via SQLAlchemy.

For each backend we boot the example API on a free port via the multi-interface
dispatcher (``python -m example.main --interface api --backend <backend>``),
exercise the relevant lifecycle, and assert on the persistence outcome.

Each test runs in its own ``tmp_path`` with a fresh copy of ``example/`` and
an isolated database file (for the SQLite case). The repo's tracked
``example/data`` directory is never written to.

Marked ``@pytest.mark.slow`` — these tests start real subprocesses.
"""

from __future__ import annotations

import shutil
import sys
import time

import httpx
import pytest

from algomancy_utils._smoke_helpers import (
    REPO_ROOT,
    find_free_port,
    live_subprocess,
    wait_for_http,
)

pytestmark = pytest.mark.slow

_ALGO = "Instant"
_ALGO_PARAMS: dict = {}
_SCENARIO_TAG = "persistence-smoke"
_STARTUP_TIMEOUT = 60.0
_RUN_TIMEOUT = 15.0


def _copy_example_dir(tmp_path) -> None:
    """Mirror ``example/`` into ``tmp_path`` so the subprocess can find data
    via the dispatcher's hardcoded relative ``example/data`` path, while keeping
    the repo's working tree untouched."""
    shutil.copytree(REPO_ROOT / "example", tmp_path / "example")


def _api_cmd(port: int, backend: str, database_url: str | None = None) -> list[str]:
    cmd = [
        sys.executable,
        "-m",
        "example.main",
        "--interface",
        "api",
        "--backend",
        backend,
        "--port",
        str(port),
    ]
    if database_url:
        cmd += ["--database-url", database_url]
    return cmd


def _create_and_run_scenario(
    base_url: str, session_id: str, dataset_key: str, tag: str
) -> str:
    """Create a scenario, enqueue it, poll until complete. Return scenario id.

    The example wires the ScenarioManager with ``autorun=True``, which means
    ``create_scenario`` already enqueues the scenario for processing — with a
    fast algorithm it can even finish before the next HTTP call. So we only
    issue an explicit ``/run`` when the scenario is still in ``created``
    status; otherwise we rely on the autorun pipeline and poll for completion.
    """
    create = httpx.post(
        f"{base_url}/api/v1/sessions/{session_id}/scenarios",
        json={
            "tag": tag,
            "dataset_key": dataset_key,
            "algo_name": _ALGO,
            "algo_params": _ALGO_PARAMS,
        },
    )
    assert create.status_code == 201, (
        f"create-scenario failed: {create.status_code} {create.text}"
    )
    created = create.json()
    scenario_id = created["id"]

    if created.get("status") == "created":
        run = httpx.post(
            f"{base_url}/api/v1/sessions/{session_id}/scenarios/{scenario_id}/run"
        )
        assert run.status_code == 202, f"run failed: {run.status_code} {run.text}"

    deadline = time.monotonic() + _RUN_TIMEOUT
    last_status: str | None = None
    while time.monotonic() < deadline:
        r = httpx.get(
            f"{base_url}/api/v1/sessions/{session_id}/scenarios/{scenario_id}/status"
        )
        last_status = r.json()["status"]
        if last_status in ("complete", "failed"):
            break
        time.sleep(0.2)
    assert last_status == "complete", (
        f"Scenario did not complete within {_RUN_TIMEOUT}s (last status: {last_status})"
    )

    return scenario_id


def _get_session_and_dataset(base_url: str) -> tuple[str, str]:
    sessions = httpx.get(f"{base_url}/api/v1/sessions").json()
    sid = sessions["default"]
    data_keys = httpx.get(f"{base_url}/api/v1/sessions/{sid}/data").json()["keys"]
    assert data_keys, f"No datasets exposed by session {sid!r}"
    return sid, data_keys[0]


def _list_scenario_tags(base_url: str, sid: str) -> list[str]:
    scenarios = httpx.get(f"{base_url}/api/v1/sessions/{sid}/scenarios").json()
    # The API returns either a bare list of scenario objects or a dict
    # wrapping it under "scenarios" depending on framework version; accept both.
    if isinstance(scenarios, dict):
        scenarios = scenarios.get("scenarios", [])
    return [s.get("tag") for s in scenarios]


def _run_backend_lifecycle(
    tmp_path,
    backend: str,
    expect_survives: bool,
    tag_suffix: str,
    *,
    database_url: str | None = None,
) -> None:
    """Run a single create-then-restart cycle and assert persistence behaviour."""
    _copy_example_dir(tmp_path)
    tag = f"{_SCENARIO_TAG}-{tag_suffix}"

    # ── Phase 1: create + run a scenario ─────────────────────────────────
    port = find_free_port()
    base_url = f"http://127.0.0.1:{port}"
    log_path = tmp_path / f"api-{backend}-create.log"

    with live_subprocess(
        _api_cmd(port, backend, database_url),
        log_path=log_path,
        cwd=tmp_path,
    ) as proc:
        wait_for_http(
            f"{base_url}/health",
            timeout_seconds=_STARTUP_TIMEOUT,
            proc=proc,
            log_path=log_path,
        )
        sid, dataset_key = _get_session_and_dataset(base_url)
        _create_and_run_scenario(base_url, sid, dataset_key, tag)
        # Sanity-check: scenario exists in this run.
        assert tag in _list_scenario_tags(base_url, sid), (
            f"Created scenario {tag!r} not visible in first run."
        )

    # ── Phase 2: restart same backend, check persistence ─────────────────
    port2 = find_free_port()
    base_url2 = f"http://127.0.0.1:{port2}"
    log_path2 = tmp_path / f"api-{backend}-restart.log"

    with live_subprocess(
        _api_cmd(port2, backend, database_url),
        log_path=log_path2,
        cwd=tmp_path,
    ) as proc2:
        wait_for_http(
            f"{base_url2}/health",
            timeout_seconds=_STARTUP_TIMEOUT,
            proc=proc2,
            log_path=log_path2,
        )
        sid2, _ = _get_session_and_dataset(base_url2)
        tags = _list_scenario_tags(base_url2, sid2)
        if expect_survives:
            assert tag in tags, (
                f"Expected {tag!r} to survive restart with backend={backend}; "
                f"tags present: {tags}"
            )
        else:
            assert tag not in tags, (
                f"Expected {tag!r} to be absent after restart with backend={backend}; "
                f"tags present: {tags}"
            )


@pytest.mark.slow
def test_none_backend_starts_with_no_persisted_scenarios(tmp_path):
    """Backend=none: stateless data manager + no scenario persistence.

    A fresh boot exposes the ``main`` session with no datasets and no
    scenarios — the absence of persistence is exactly the point. This
    behaviour is what makes ``backend=none`` distinct from the json/database
    variants below.
    """
    _copy_example_dir(tmp_path)
    port = find_free_port()
    base_url = f"http://127.0.0.1:{port}"
    log_path = tmp_path / "api-none.log"

    with live_subprocess(
        _api_cmd(port, "none"),
        log_path=log_path,
        cwd=tmp_path,
    ) as proc:
        wait_for_http(
            f"{base_url}/health",
            timeout_seconds=_STARTUP_TIMEOUT,
            proc=proc,
            log_path=log_path,
        )
        sessions = httpx.get(f"{base_url}/api/v1/sessions").json()
        sid = sessions["default"]
        tags = _list_scenario_tags(base_url, sid)
        assert tags == [], (
            f"backend=none should never expose persisted scenarios on cold boot; got {tags}"
        )


@pytest.mark.slow
def test_json_backend_loads_data_across_restart(tmp_path):
    """Backend=json: data is persisted, scenario *registry* is in-memory only.

    Two boots on the same data folder both expose the same dataset keys and
    auto-create scenarios that depend on them. User-created scenarios do NOT
    survive — json scenario-registry persistence is not implemented in the
    framework. (The database backend below covers full scenario persistence.)
    """
    _copy_example_dir(tmp_path)

    user_tag = f"{_SCENARIO_TAG}-user-json"

    def _datasets_and_tags(base_url: str) -> tuple[list[str], list[str]]:
        sid = httpx.get(f"{base_url}/api/v1/sessions").json()["default"]
        keys = httpx.get(f"{base_url}/api/v1/sessions/{sid}/data").json()["keys"]
        return keys, _list_scenario_tags(base_url, sid)

    # Phase 1: boot, observe data + auto-scenarios, create a user scenario.
    port = find_free_port()
    base_url = f"http://127.0.0.1:{port}"
    log_path = tmp_path / "api-json-1.log"
    with live_subprocess(_api_cmd(port, "json"), log_path=log_path, cwd=tmp_path) as p:
        wait_for_http(
            f"{base_url}/health",
            timeout_seconds=_STARTUP_TIMEOUT,
            proc=p,
            log_path=log_path,
        )
        keys1, tags1 = _datasets_and_tags(base_url)
        assert keys1, "json backend should expose datasets loaded from the data folder"
        sid = httpx.get(f"{base_url}/api/v1/sessions").json()["default"]
        _create_and_run_scenario(base_url, sid, keys1[0], user_tag)
        assert user_tag in _list_scenario_tags(base_url, sid), (
            "user scenario should be present in the same run"
        )

    # Phase 2: cold boot; data + auto-scenarios should reappear, user scenario should NOT.
    port2 = find_free_port()
    base_url2 = f"http://127.0.0.1:{port2}"
    log_path2 = tmp_path / "api-json-2.log"
    with live_subprocess(
        _api_cmd(port2, "json"), log_path=log_path2, cwd=tmp_path
    ) as p:
        wait_for_http(
            f"{base_url2}/health",
            timeout_seconds=_STARTUP_TIMEOUT,
            proc=p,
            log_path=log_path2,
        )
        keys2, tags2 = _datasets_and_tags(base_url2)
        assert set(keys2) == set(keys1), (
            f"json backend should expose the same data keys on restart; "
            f"first={keys1!r} second={keys2!r}"
        )
        assert user_tag not in tags2, (
            f"json backend does not persist user-created scenarios; "
            f"unexpected survival of {user_tag!r} in {tags2!r}"
        )


@pytest.mark.slow
def test_database_backend_scenarios_survive_restart(tmp_path):
    """Backend=database (SQLite): scenarios survive restart via the DB."""
    # SQLAlchemy is an optional extra (``algomancy-scenario[database]``).
    # Skip the database test in environments where it isn't installed —
    # otherwise the subprocess crashes with a confusing ImportError.
    pytest.importorskip(
        "sqlalchemy",
        reason="install with `uv sync --extra database` to enable the SQLite persistence smoke",
    )
    db_url = f"sqlite:///{(tmp_path / 'persistence_smoke.db').as_posix()}"
    _run_backend_lifecycle(
        tmp_path,
        "database",
        expect_survives=True,
        tag_suffix="database",
        database_url=db_url,
    )
