"""ScenarioRepository protocol.

Defines the storage contract for scenarios. Both ``ScenarioRegistry``
(in-memory) and ``SqlScenarioRepository`` (database-backed) conform to this
interface, so ``ScenarioManager`` can accept either without branching.
"""

from typing import List, Optional, Protocol, runtime_checkable

from ..scenario import Scenario


@runtime_checkable
class ScenarioRepository(Protocol):
    def add(self, scenario: Scenario) -> None: ...
    def get_by_id(self, scenario_id: str) -> Optional[Scenario]: ...
    def get_by_tag(self, tag: str) -> Optional[Scenario]: ...
    def delete(self, scenario_id: str) -> bool: ...
    def list(self) -> List[Scenario]: ...
    def list_ids(self) -> List[str]: ...
    def list_tags(self) -> List[str]: ...
    def has_tag(self, tag: str) -> bool: ...
    def used_datasets(self) -> List[str]: ...
