from dash import html, get_app, callback, Output, Input

from algomancy_gui.componentids import OVERVIEW_PAGE_CONTENT, ACTIVE_SESSION
from algomancy_gui.contentregistry import ContentRegistry
from algomancy_gui.managergetters import get_scenario_manager
from algomancy_scenario import ScenarioManager


def overview_page():
    """
    Creates the overview page content container. The standard implementation of this page displays a table where
     rows represent completed scenarios and columns represent KPIs. The page is to be rendered by a callback dependent
     on the active session.

    Returns:
        html.Div: A Dash HTML component to contain the overview page content.
    """
    return html.Div(id=OVERVIEW_PAGE_CONTENT)


@callback(Output(OVERVIEW_PAGE_CONTENT, "children"), Input(ACTIVE_SESSION, "data"))
def render_overview_page(active_session_name):
    """
    Renders the overview page content based on the active session. The content is generated by the content registry
    using the list of scenarios from the scenario manager.

    Args:
        active_session_name (str): The name of the active session.

    Returns:
        html.Div: A Dash HTML component representing the overview page content.
    """
    server = get_app().server

    cr: ContentRegistry = server.content_registry
    sm: ScenarioManager = get_scenario_manager(server, active_session_name)

    return cr.overview_content(sm.list_scenarios())
