# language: yaml
variables:
  python.version: 3.14
  publish: 'false'   # set to 'true' when you want to actually upload to feed
trigger:
  - main
name: $(date:yyyyMMdd)$(rev:.r)
stages:
  - stage: __default
    jobs:
      - job: Phase_1
        displayName: Publish
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UsePythonVersion@0
            displayName: Use Python $(python.version)
            inputs:
              versionSpec: $(python.version)

          - task: CmdLine@2
            displayName: Upgrade pip and install uv, build and publishing tools
            inputs:
              script: |
                python -m pip install --upgrade pip
                python -m pip install uv build twine keyring artifacts-keyring

          - task: CmdLine@2
            displayName: Install project dependencies with uv (workspace-aware)
            inputs:
              script: |
                uv sync --frozen

          - task: CmdLine@2
            displayName: Validate lockfile
            inputs:
              script: |
                uv lock --check || (echo "Lockfile out of date" && exit 1)

          - task: CmdLine@2
            displayName: Build source and wheels with uv
            inputs:
              script: |
                uv build --wheel

          - task: PublishPipelineArtifact@1
            displayName: Publish dist artifacts
#            condition: eq(variables['publish'], 'true')
            inputs:
              targetPath: 'dist'
              artifact: 'dist'
              publishLocation: 'pipeline'

          - task: TwineAuthenticate@1
            displayName: 'Twine authenticate'
            condition: eq(variables['publish'], 'true')
            inputs:
              artifactFeed: WARP/WarpPython

          - task: CmdLine@2
            displayName: Upload to feed
            condition: eq(variables['publish'], 'true')
            inputs:
              script: twine upload --config-file $(PYPIRC_PATH) --verbose -r WarpPython dist/*