# language: yaml
variables:
  python.version: 3.14
trigger:
  - main
name: $(date:yyyyMMdd)$(rev:.r)
stages:
  - stage: __default
    displayName: Build-Test-Publish
    jobs:

      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UsePythonVersion@0
            displayName: Use Python $(python.version)
            inputs:
              versionSpec: $(python.version)

          - task: CmdLine@2
            displayName: Upgrade pip and install uv and build tools
            inputs:
              script: |
                python -m pip install --upgrade pip
                python -m pip install uv build

          - task: CmdLine@2
            displayName: Install project dependencies with uv (workspace-aware)
            inputs:
              script: |
                uv sync --frozen

          - task: CmdLine@2
            displayName: Validate lockfile
            inputs:
              script: |
                uv lock --check || (echo "Lockfile out of date" && exit 1)

          - task: CmdLine@2
            displayName: Build source and wheels with uv
            inputs:
              script: |
                uv build --all-packages --wheel

          - task: PublishPipelineArtifact@1
            displayName: Publish dist artifacts
            inputs:
              targetPath: 'dist'
              artifact: 'dist'
              publishLocation: 'pipeline'

      - job: Publish
        displayName: Publish to PyPI
        dependsOn:
          - Build
        condition: succeeded()
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UsePythonVersion@0
            displayName: Use Python $(python.version)
            inputs:
              versionSpec: $(python.version)

          - task: CmdLine@2
            displayName: Install uv
            inputs:
              script: |
                python -m pip install --upgrade pip
                python -m pip install uv

          - task: DownloadPipelineArtifact@2
            displayName: Download dist artifact
            inputs:
              artifact: 'dist'
              path: 'dist_downloaded'

          - task: CmdLine@2
            displayName: Upload to PyPI with uv
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            env:
              UV_PUBLISH_TOKEN: $(PyPI.Token)
            inputs:
              script: |
                uv publish --token $UV_PUBLISH_TOKEN dist_downloaded/*